Repository jmcheon/matcha, pull requests merged in 2024-09, with the labels that each got.

#15 chore: dark mode for navbar
  .vscode/settings.json
  front-nuxt/TODO.md
  front-nuxt/components/DarkModeSelector.vue
  front-nuxt/components/LanguageSelector.vue
  front-nuxt/components/LoginSelector.vue
  front-nuxt/components/MenuSelector.vue
  front-nuxt/components/TheFooter.vue
  front-nuxt/components/TheNavbar.vue
Labels: UI

#17 feat: forgot password 구현
  back-express/src/controllers/account.controller.ts
  back-express/src/controllers/auth.controller.ts
  back-express/src/models/account.model.ts
  back-express/src/routes/account.routes.ts
  back-express/src/routes/auth.routes.ts
  back-express/src/services/email.service.ts
  front-nuxt/composables/useAuth.ts
  front-nuxt/composables/useProfile.ts
  front-nuxt/langs/en.json
  front-nuxt/langs/fr.json
  front-nuxt/pages/auth/forgot-password.vue
  front-nuxt/pages/auth/register.vue
  front-nuxt/pages/auth/reset-email-sent.vue
  front-nuxt/pages/auth/reset-password.vue
  front-nuxt/types/index.ts
  init_db(TEST).sh
Labels: enhancement

#18 fix: social login logging in with email fixed
  back-express/src/controllers/auth.controller.ts
  back-express/src/passport/googleStrategy.ts
  front-nuxt/langs/en.json
  front-nuxt/langs/fr.json
  front-nuxt/pages/auth/register.vue
  front-nuxt/pages/error.vue
Labels: bug

#25 feat: upload profile image
  .gitignore
  back-express/images/.gitkeep
  back-express/package.json
  back-express/src/app.ts
  back-express/src/controllers/auth.controller.ts
  back-express/src/controllers/profile.controller.ts
  back-express/src/models/account.model.ts
  back-express/src/models/profile.model.ts
  back-express/src/passport/googleStrategy.ts
  back-express/src/routes/account.routes.ts
  back-express/src/routes/profile.routes.ts
  db-mysql/scripts/generate_table.sql
  front-nuxt/components/TheNavbar.vue
  front-nuxt/composables/useAuth.ts
  front-nuxt/composables/useAxios.ts
  front-nuxt/composables/useProfile.ts
  front-nuxt/composables/userValidator.ts
  front-nuxt/langs/en.json
  front-nuxt/langs/fr.json
  front-nuxt/middleware/strict-auth.ts
  front-nuxt/nuxt.config.ts
  front-nuxt/pages/auth/forgot-password.vue
  front-nuxt/pages/auth/generate-profile.vue
  front-nuxt/pages/auth/login.vue
  front-nuxt/pages/auth/register.vue
  front-nuxt/pages/auth/reset-email-sent.vue
  front-nuxt/pages/auth/reset-password.vue
  front-nuxt/pages/auth/upload-profile-image.vue
  front-nuxt/pages/auth/verify-email.vue
  front-nuxt/pages/error.vue
  front-nuxt/pages/home.vue
  front-nuxt/plugins/01.init.ts
  front-nuxt/stores/account.store.ts
  front-nuxt/stores/user.store.ts
  front-nuxt/types/index.ts
Labels: enhancement

#28 chore: updated package.json for both
  back-express/package.json
  front-nuxt/package.json
Labels: enhancement
