Repository jmcheon/matcha, pull requests merged in 2024-10, with the labels that each got.

#29 feat: complete implementing oauth
  back-express/package.json
  back-express/src/controllers/auth.controller.ts
  back-express/src/models/account.model.ts
  back-express/src/passport/SocialInfo.ts
  back-express/src/passport/ftStrategy.ts
  back-express/src/passport/githubStrategy.ts
  back-express/src/passport/googleStrategy.ts
  back-express/src/passport/index.ts
  back-express/src/routes/auth.routes.ts
  db-mysql/scripts/generate_table.sql
  front-nuxt/composables/useAuth.ts
  front-nuxt/langs/en.json
  front-nuxt/package.json
  front-nuxt/pages/auth/login.vue
  front-nuxt/pages/auth/register.vue
Labels: enhancement

#31 feat: oauth import photo
  back-express/src/controllers/auth.controller.ts
  back-express/src/controllers/profile.controller.ts
  back-express/src/models/account.model.ts
  back-express/src/passport/ftStrategy.ts
  back-express/src/passport/githubStrategy.ts
  back-express/src/passport/googleStrategy.ts
  back-express/src/routes/profile.routes.ts
  back-express/src/services/auth.service.ts
  back-express/src/services/email.service.ts
  back-express/src/services/profile.service.ts
  db-mysql/scripts/generate_table.sql
  front-nuxt/composables/useAuth.ts
  front-nuxt/composables/useProfile.ts
  front-nuxt/composables/userValidator.ts
  front-nuxt/langs/en.json
  front-nuxt/langs/fr.json
  front-nuxt/pages/auth/generate-profile.vue
  front-nuxt/pages/auth/upload-profile-image.vue
  front-nuxt/plugins/01.init.ts
  front-nuxt/stores/user.store.ts
  front-nuxt/types/index.ts
Labels: enhancement

#43 fastapi - register
  .gitignore
  Dockerfile.back
  back-fastapi/__pycache__/main.cpython-39.pyc
  back-fastapi/main.py
  back-fastapi/requirements.txt
  back-fastapi/src/__init__.py
  back-fastapi/src/controllers/auth_controller.py
  back-fastapi/src/middlewares/cors_middleware.py
  back-fastapi/src/models/db.py
  back-fastapi/src/models/dto.py
  back-fastapi/src/models/validators.py
  back-fastapi/src/repositories/account_repository.py
  back-fastapi/src/services/account_service.py
  back-fastapi/src/services/auth_service.py
  docker-compose.dev.yml
  front-nuxt/composables/useAuth.ts
  front-nuxt/nuxt.config.ts
  server-nginx/conf/nginx.conf
Labels: backend

#47 fastapi - verify email update
  back-fastapi/constants.py
  back-fastapi/src/controllers/auth_controller.py
  back-fastapi/src/models/db.py
  back-fastapi/src/repositories/account_repository.py
  back-fastapi/src/services/account_service.py
  back-fastapi/src/services/auth_service.py
  back-fastapi/src/services/email_service.py
  front-nuxt/composables/useAuth.ts
  front-nuxt/pages/auth/register.vue
Labels: bug, backend

#50 chore: update .env and fastapi code to use default port
  Dockerfile.back
  back-fastapi/constants.py
  back-fastapi/src/services/email_service.py
  docker-compose.dev.yml
  front-nuxt/composables/useAuth.ts
  front-nuxt/nuxt.config.ts
  server-nginx/conf/nginx.conf
Labels: backend

#51 fastapi - login/out & forgot/reset password
  .vscode/settings.json
  back-fastapi/constants.py
  back-fastapi/main.py
  back-fastapi/requirements.txt
  back-fastapi/src/controllers/account_controller.py
  back-fastapi/src/controllers/auth_controller.py
  back-fastapi/src/middlewares/token_required.py
  back-fastapi/src/repositories/account_repository.py
  back-fastapi/src/services/account_service.py
  back-fastapi/src/services/auth_service.py
  back-fastapi/src/services/email_service.py
  docker-compose.dev.yml
  front-nuxt/composables/useAccount.ts
  front-nuxt/composables/useAuth.ts
  front-nuxt/composables/useProfile.ts
  front-nuxt/nuxt.config.ts
  front-nuxt/pages/auth/forgot-password.vue
  front-nuxt/pages/auth/login.vue
  front-nuxt/pages/auth/reset-password.vue
  server-nginx/conf/nginx.conf
Labels: backend

#54 fix: apply ruff and fixed code except account
  .vscode/settings.json
  back-fastapi/constants.py
  back-fastapi/main.py
  back-fastapi/pyproject.toml
  back-fastapi/requirements-dev.txt
  back-fastapi/requirements.txt
  back-fastapi/src/controllers/account_controller.py
  back-fastapi/src/controllers/auth_controller.py
  back-fastapi/src/middlewares/cors_middleware.py
  back-fastapi/src/middlewares/token_required.py
  back-fastapi/src/models/db.py
  back-fastapi/src/models/dto.py
  back-fastapi/src/repositories/account_repository.py
  back-fastapi/src/services/account_service.py
  back-fastapi/src/services/auth_service.py
  back-fastapi/src/services/email_service.py
Labels: enhancement

#57 refactort: validator and dto
  .gitignore
  alias.sh
  back-express/src/models/account.model.ts
  back-fastapi/constants.py
  back-fastapi/src/controllers/auth_controller.py
  back-fastapi/src/middlewares/token_required.py
  back-fastapi/src/models/__init__.py
  back-fastapi/src/models/dto.py
  back-fastapi/src/models/validators.py
  back-fastapi/src/repositories/account_repository.py
  back-fastapi/src/services/account_service.py
  back-fastapi/src/services/auth_service.py
  back-fastapi/src/services/email_service.py
  front-nuxt/composables/useAuth.ts
  front-nuxt/composables/useAxios.ts
  front-nuxt/pages/auth/register.vue
  front-nuxt/plugins/01.init.ts
  front-nuxt/stores/user.store.ts
  front-nuxt/types/index.ts
  miniconda_setup.sh
Labels: enhancement

#59 refactor: profile to fastapi #1
  back-fastapi/main.py
  back-fastapi/src/controllers/auth_controller.py
  back-fastapi/src/controllers/profile_controller.py
  back-fastapi/src/models/dtos/account_dto.py
  back-fastapi/src/models/dtos/profile_dto.py
  back-fastapi/src/models/validators.py
  back-fastapi/src/repositories/account_repository.py
  back-fastapi/src/repositories/profile_repository.py
  back-fastapi/src/services/account_service.py
  back-fastapi/src/services/auth_service.py
  back-fastapi/src/services/email_service.py
  back-fastapi/src/services/profile_service.py
  front-nuxt/composables/useProfile.ts
  front-nuxt/pages/auth/generate-profile.vue
Labels: backend

#60 feat: email verification redirections
  back-fastapi/src/controllers/account_controller.py
  back-fastapi/src/controllers/auth_controller.py
  back-fastapi/src/middlewares/token_required.py
  back-fastapi/src/models/dtos/account_dto.py
  back-fastapi/src/models/validators.py
  back-fastapi/src/repositories/account_repository.py
  back-fastapi/src/services/account_service.py
  back-fastapi/src/services/auth_service.py
  back-fastapi/src/services/email_service.py
  front-nuxt/composables/useAuth.ts
  front-nuxt/langs/en.json
  front-nuxt/langs/fr.json
  front-nuxt/pages/auth/login.vue
  front-nuxt/pages/auth/verify-email.vue
Labels: enhancement
